FROM rust:latest as builder
RUN cargo install --git https://github.com/nanpuyue/sock5s.git

FROM ubuntu:latest
COPY --from=builder /usr/local/cargo/bin/sock5s /usr/local/bin
RUN apt update &&\
    apt install -y jq openresolv openvpn &&\
    apt clean

WORKDIR /vpn
EXPOSE 1080
ADD docker-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]
